### ISSUE TITLE
StereoMenuControl BP issue

### ISSUE THREAD

**Issue by ghost** [nullboundary/UnrealPanoramaMenu#1]
Plugin does not work for me. When i make search about it, i found that StereoMenuControl BP does not compile and gives error on Remove From Parent And Construct NONE. 
Please help
![1](https://cloud.githubusercontent.com/assets/18577008/17595897/b1f16742-5ff7-11e6-9024-1e363b5e1e83.png)

**Comment by nullboundary** [comment]
Hi,

Yeah this is an error I just noticed when you add the blueprints to a new project. The reference to Stereo Menu Widget is broken. 
1. The solution is to connect the StereoMenuWidget (Get) With the IsValid node and to Remove from Parent node. Also don't forget to connect StereoMenuWidget (Get to the "Set Input mode Game and UI" node. Its over on the right side of the blueprint. It doesn't give an error but it will cause the menu to behave strangely if you don't. 
2. Also select the StereoMenuWidget variable type and set it to Stereo Menu its currently set to object and won't connect to Remove from Parent node. 
3. For the Construct class node if you use the select class drop down you can select the stereomenuwidget class. 

Sorry for all the issues. I am working on a way to make it work without these problems. Its all do to issues with importing the blueprints into a new project.

**Comment by pakjalil93** [comment]
nullboundary  sir can u please show the image of solution or can you tell a little video...
Atleast please upload the image of solution thanks.......

**Comment by nullboundary** [comment]
Ok, I just updated the component. It should work as instructed in the README now without any errors. Please let me know if its still not working. Its been tested in ue4 4.14.

**Comment by pakjalil93** [comment]
Thank u very much sir I surely check and tell u........
